### ISSUE TITLE
can not get wifi ssid

### ISSUE THREAD

**Issue by dfengpo** [exendahal/WifiManagerMAUI#1]
I am use andriod 13 device to debug NetworkInfo.OnAppearing method.
I get unkonw ssid.

![image](https://github.com/exendahal/WifiManagerMAUI/assets/12029452/9dee3cf0-26d9-44f8-83fd-b27fc703c6e7)

And this code get list cout=0
  var response = await CrossWifiManager.Current.ScanWifiNetworks();
![image](https://github.com/exendahal/WifiManagerMAUI/assets/12029452/ba31f9f9-c954-4167-b082-89342bb8c0be)

**Comment by exendahal** [comment]
Can you confirm that you are testing the code on a physical device and that the location service for the device is turned on?

**Comment by exendahal** [comment]
Resolves with version [1.0.2](https://github.com/exendahal/WifiManagerMAUI/commit/0be3f9ab688c37278718a0754b981e5065f83980)

**Comment by dfengpo** [comment]
thank you
